dist: xenial

language: generic
sudo: required

cache:
  directories:
    - $HOME/.m2

services:
  - docker

branches:
  only:
    - master
    - develop

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.447.sh
  - chmod +x linux-install-1.10.1.447.sh
  - sudo ./linux-install-1.10.1.447.sh

before_script:
  - env | sort
  - node --version
  - java -version

script:
  - clojure -Adev tools.clj build:test
  - node out/tests.js
  - clojure -Adev:test
